### ISSUE TITLE
SendGrid Setup replies don't seem to arrive

### ISSUE THREAD

**Issue by dvrcthewrld** [r-a-y/bp-reply-by-email#100]
Emails are generated fine and reach users' email inboxes. When they reply, SendGrid registeres their reply in the Activity log, but my site shows nothing. And there's no RBE debug file.

**Comment by jasonvarone** [comment]
I have the same exact problem. I see that the emails are parsed on the SendGrid activity log, but nothing posts my site, and there is no RBE debug file. My install of Commons in a Box is set up as a private environment, could that be conflicting with the RBE plugin?

**Comment by r-a-y** [comment]
About the RBE log path, it's probably a permissions issue.

Try setting the path manually to the uploads folder:
`define( 'BP_RBE_DEBUG_LOG_PATH', WP_CONTENT_DIR . '/uploads/bp-rbe-debug.log' );`

I'll probably default the log path to this directory in the future.

----

>  My install of Commons in a Box is set up as a private environment, could that be conflicting with the RBE plugin?

@jasonvarone - Yes, since the webhook needs to ping your site, the URL you provided to SendGrid must be publicly-available.

**Comment by jasonvarone** [comment]
@r-a-y The site is not entirely private, but the forums are. Does that matter? 

I'm a member of NYCDH. Doest that mean that any of the private groups on that site (like the NYCDH Website Team) are unable to use Reply by Email? Thanks for the reply.

**Comment by r-a-y** [comment]
> The site is not entirely private, but the forums are. Does that matter?

By private, I thought you meant that you blocked off access to the site via a redirect rule.

All that matters is what you entered for the webhook URL in SendGrid and whether that URL is accessible.  If that URL is not publicly accessible, then SendGrid cannot post their response to the site and subsequently, RBE cannot parse that response.

Ensure that you've made the change so the RBE debug log is written to the uploads folder.  Next, see if anything is written to the RBE debug log after you have sent a reply.

**Comment by r-a-y** [comment]
@jasonvarone @dvrcthewrld I've set the default log path to use the uploads directory in commit a8cb0fc.

Let me know if you can test with SendGrid again.

**Comment by jasonvarone** [comment]
I'll have a chance to try this another time next week. Many thanks @r-a-y

**Comment by boonebgorges** [comment]
It looks like SendGrid may have changed its `User-Agent` header. Here's what I see in its POST requests: `Sendlib/1.0 mx0017p1las1.sendgrid.net`. When I make the manual change to `BP_Reply_By_Email_Inbound_Provider_SendGrid::webhook_parser()`, emails are processed as expected. @r-a-y Are you able to confirm?

**Comment by r-a-y** [comment]
Thanks for looking into this, @boonebgorges.

It'll take me a few days to look into the SendGrid user agent, but I trust your report :smile:

If you want to, can you send a PR to change the check of the user agent from `SendGrid` to `Sendlib`?  Otherwise, I'll verify the user agent change and commit the fix.

**Comment by r-a-y** [comment]
@jasonvarone @dvrcthewrld - @boonebgorges provided a fix for SendGrid parsing, so once you are able to test again, pull the latest changes from Github, or download the latest master branch for testing:
https://github.com/r-a-y/bp-reply-by-email/archive/master.zip

**Comment by dvrcthewrld** [comment]
Up and running smoothly. Thank you.

**Comment by jasonvarone** [comment]
Yes, I can confirm this is up and running for me too. Many thanks!
