### ISSUE TITLE
"Masking" the long name

### ISSUE THREAD

**Issue by emeyal** [r-a-y/bp-reply-by-email#102]
Hi,

Is there a way to mask the long name provided by Postmark (xxx@inbound.postmarkapp.com) with a  comprehensible name, say "MyForum <xxx@inbound.postmarkapp.com>"  ?

Thank you for setting up this important plugin.
Eyal

**Comment by r-a-y** [comment]
I did do this originally, but it conflicted with the Apple Mail app so I reverted the change.

See commit 17b4799f9dce26d5235c63378f57cc51cc8b2a28.

**Comment by emeyal** [comment]
Thank you very much Ray!
Eyal
