### ISSUE TITLE
bbPress: Support attachments

### ISSUE THREAD

**Issue by r-a-y** [r-a-y/bp-reply-by-email#104]
If using RBE to reply to a bbPress topic, we should try and parse email attachments if available and post it.

This will currently have to rely on the GD bbPress Attachments plugin being active.

The problem here is I do not want to parse email attachments unless it is a bbPress item.  But with the way the codebase is currently structured,  the parameters are checked inside the RBE parsing logic.

We need access to the RBE parameters _before_ initializing the parser.  This will require some code refactoring.

Supporting both IMAP and all the Inbound Providers will also increase implementation time.

- [x] IMAP
- [x] Inbound Mail - SparkPost ([via plugin](https://github.com/r-a-y/bp-rbe-inbound-forum-attachments))
- [ ] Inbound Mail - SendGrid
- [ ] Inbound Mail - Postmark

**Comment by modelm** [comment]
Humanities Commons would love to be able to use this feature with SparkPost. Has there been any progress for that provider? Is there anything I should know before (potentially, soon-ish) setting out to implement it and subsequently PR?

**Comment by r-a-y** [comment]
I'm working on it.  Should be about a week or so away from testing.

**Comment by modelm** [comment]
Awesome! Looking forward to trying it out.

**Comment by r-a-y** [comment]
@modelm - I decided to move forum attachment support for inbound providers to a new plugin:
https://github.com/r-a-y/bp-rbe-inbound-forum-attachments

Give it a test and report issues on that repo if you find any.

**Comment by r-a-y** [comment]
Closing.  SendGrid and Postmark will be covered in the plugin mentioned above.
