### ISSUE TITLE
Using bp_rbe_show_non_rbe_notice filter

### ISSUE THREAD

**Issue by dvrcthewrld** [r-a-y/bp-reply-by-email#106]
I see that you included a filter to allow for a means of excluding the nonrbe notice from being prepended to certain emails.  Could you provide an example for its use?  I'd very much like to stop this from being prepended to WooCommerce emails.  Thank you.

**Comment by r-a-y** [comment]
Here's an older answer I gave that might help:
https://wordpress.org/support/topic/selectively-use-reply-by-email-avoid-woocommerce-newsletter-etc/

Otherwise, I can't provide support for commercial endeavors.
