### ISSUE TITLE
Would it be possible to add cPanel Pipe to Program option?

### ISSUE THREAD

**Issue by normancates** [r-a-y/bp-reply-by-email#113]
Hi ya,
The piping facility obviously can be really useful.

But it's actually pretty hard to set up for the external providers.

But cPanel has the ability to pipe forwarded emails to a program.

It looks really easy to set up, and keeps it all within the web management environment. 

Could this be added as a piping option?

Cheers,
Norm

**Comment by r-a-y** [comment]
Anything is possible, but I most likely will not be implementing this.

**Comment by normancates** [comment]
Fair enough. It's just that the other piping options are really incredibly complicated. The IMAP setup is vastly easier. And I have it running with my own server.

I don't even understand what Sparkpost is asking me to do in regards to the Relay Webhooks.

https://developers.sparkpost.com/api/relay-webhooks.html#relay-webhooks-create-and-list-post

Clearly it's assuming knowledge I don't have. Like where those commands should be run. 

Any places I can look to get some background on this?

Thanks,
Norm

**Comment by r-a-y** [comment]
> I don't even understand what Sparkpost is asking me to do in regards to the Relay Webhooks.

I mention in the [SparkPost wiki article](https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost) that SparkPost is for developers only.

You might want to give [SendGrid or Postmark](https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide#1-inbound-email-mode) a try.  The set up doesn't require needing to interact with an API or the command-line, but you'll still have to configure your DNS to set a MX record to point to either SendGrid or Postmark.

Going to close this one as I'm unlikely to add support to cPanel Pipe.  However, feel free to continue replying.
