### ISSUE TITLE
RBE fails after CBOX update

### ISSUE THREAD

**Issue by jasonvarone** [r-a-y/bp-reply-by-email#119]
Has anyone encountered issues with Reply By Email after doing a CBOX update? RBE stopped working for me with the latest update. I updated WP to 5.0.2, then followed the CBOX update prompt. The site hung in maintenance mode for 10 minutes while trying to update RBE. Then the plugin stopped working.

I get a "no such file or directory" warning - bp-rbe-functions.php is missing?

**Comment by r-a-y** [comment]
@jasonvarone - Sorry for the late reply.

Can you tell me what folder RBE is located in your `wp-content/plugins` directory?  Is there any directory beginning with `bp-reply-by-email`?  If not, did it get removed during the CBOX update and fail to extract the latest files?

If a RBE directory doesn't exist, grab the latest version of the plugin [here](https://github.com/r-a-y/bp-reply-by-email/archive/1.0-RC7.zip).  Rename the folder to `bp-reply-by-email` and try reactivating.

Let me know what happens.

**Comment by jasonvarone** [comment]
@r-a-y Thanks for the reply. 

The folder did exist, but I went ahead and replaced it anyway with the latest version. I renamed it `bp-reply-by-email` and re-activated the plugin. It still doesn't work though. 

It's configured with SendGrid but the emails are not even showing up on my account there. The emails do contain "--- Reply ABOVE THIS LINE to add a comment ---" so something is working.

Any ideas?

**Comment by jasonvarone** [comment]
I recently switched [the site](https://printcouncil.org/) to https, and I didn't actually test RBE after that - could that be the reason it's not working?

**Comment by r-a-y** [comment]
> I recently switched the site to https, and I didn't actually test RBE after that - could that be the reason it's not working?

Yes, if you use SendGrid, you will probably have to update the Inbound Parse URL endpoint to use HTTPS:
https://sendgrid.com/developer/reply

**Comment by jasonvarone** [comment]
Many thanks @r-a-y

That did the trick
