### ISSUE TITLE
[Question] No emails, when different subdomain

### ISSUE THREAD

**Issue by onliniak** [r-a-y/bp-reply-by-email#120]
Stupid question,

I have 2 different test subdomains (I can't setup DNS on forum domain):

luunube.ardoon.ga → bbPress forum
poczta.skri.ga         → post subdomain.

SendGrid setup:
 ![sg1](https://imgur.com/N4XHkCS.png)
 ![sg2](https://imgur.com/3zw7a2m.png)
 ![sg3](https://imgur.com/GoIvYOo.png)
 ![sg4](https://imgur.com/GEs4lLz.png)

My WP settings ![wp](https://imgur.com/TBF42TE.png)
MX DNS Correct https://mxtoolbox.com/SuperTool.aspx?action=mx%3apoczta.skri.ga&run=toolpage#   10 | mx.sendgrid.net
CNAME DNS Not found (?) ![cname](https://imgur.com/pztwOK7.png)
WP Mail Log from BuddyPress mention activity ("Spam e-mail") ![send](https://imgur.com/WldovKV.png)

---
I am able to send test emails via Check Email plugin, but I am not able to receive emails sended via bbPress or BuddyPress.
Should I change subdomains to newdomain.com and reply.newdomain.com ?

**Comment by r-a-y** [comment]
In the SendGrid Inbound Parse page, if your site is using HTTPS, set the URL to HTTPS instead of HTTP.

**Comment by onliniak** [comment]
Thanks for quick reply,


I solved "no-emails" problem via external SMTP (WP SendGrid SMTP plugin), but now I have new problem.

I tested webhooks with Webhooks.site → I received all 3 sended POST requests.
I mentioned another test user with @user test test test, after few minutes I received BuddyPress email, after reply … nothing.

20 minutes later I received this message:

This is the mail system at host mx0032p1mdw1.sendgrid.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<letters_and_numbers-new@poczta.skri.ga>: User unknown in virtual
    alias table
Od:Me
Do:letters_and_numbers-new@poczta.skri.ga
Wysłane:Wed May 15 21:43:30 CEST 2019
Temat: Re: [Forum] User mentioned you in a status update
Message 123

---

Virtual alias table ?

I also tried published new reply in bbPress → similar message with User unknown in virtual alias table

My site use self-signed certificate, I tested http and https. 

W dniu 14 maj 2019, 19:00, o 19:00, użytkownik r-a-y <notifications@github.com> napisał:

**Comment by r-a-y** [comment]
This isn't a problem with the plugin.  It's an email configuration issue on your server.

Google "user unknown in virtual alias table" for more info.

**Comment by onliniak** [comment]
"Mailbox not found"

I thought something was blocking the connection between SendGrid and WordPress, since Webmentions.site works.

OK, I think the problem is solved, I will try again with IMAP.

Thank you for your help.

W dniu 15 maj 2019, 22:54, o 22:54, użytkownik r-a-y <notifications@github.com> napisał:

**Comment by onliniak** [comment]
After few

Your reply could not be posted because we could not find the "--- Reply ABOVE THIS LINE to add a comment ---" marker in the body of your email

It works.

I just needed new inbound domain.

W dniu 15 maj 2019, 22:54, o 22:54, użytkownik r-a-y <notifications@github.com> napisał:
