### ISSUE TITLE
"Replying to this email will not send a message directly to the recipient or group"

### ISSUE THREAD

**Issue by lukaszliniewicz** [r-a-y/bp-reply-by-email#127]
I was able to configure the plugin using IMAP (Gmail), but every notification sent by BuddyPress includes "Replying to this email will not send a message directly to the recipient or group". I'm using WordPress 6.5, BP 12.51 and the WP SMTP plugin (it uses another gmail address to send all emails). I don't have bbPress installed and this happens for all notifications (activity posts, private messages etc.).

**Comment by r-a-y** [comment]
This was brought up in another discussion thread. Please view this for the rationale and a workaround: https://wordpress.org/support/topic/selectively-use-reply-by-email-avoid-woocommerce-newsletter-etc/
