### ISSUE TITLE
Unable to find "--- Reply ABOVE THIS LINE [...]" error

### ISSUE THREAD

**Issue by arshiacont** [r-a-y/bp-reply-by-email#57]
I just updated to the latest master, and also switched to my own IMAP server (which looks fine).

All attempts to reply by email leads to the following message. Note that the "For reference, your entire reply was:" gives an empty string which is not the case. I'm also sure that I am sending the correct email body.

**Comment by r-a-y** [comment]
I'm cleaning up a few issues in this repo.

Let me know if you are still experiencing this issue.
