### ISSUE TITLE
Plugin installation hangs

### ISSUE THREAD

**Issue by palmdoc** [r-a-y/bp-reply-by-email#58]
Just trying this beta on my site with about 100 users
The plugin installation just hangs after filling in the Gmail credentials and hitting the Save button.
Not sure what to do next

**Comment by r-a-y** [comment]
Commits f91165a and ab97ea7 should hopefully address this.

If you haven't tried RBE in some time, I would recommend Inbound Email mode instead of IMAP:
https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide#1-inbound-email-mode
