### ISSUE TITLE
Can't get reply-by-email to connect to any server

### ISSUE THREAD

**Issue by basemaly** [r-a-y/bp-reply-by-email#59]
Hi, and thanks for this great plugin. I've been trying to configure it to work with either our University's imap server or gmail, to no avail. 

After reading through the forum and reinstalling our certificates, I get the following error when I try to use our own imap server on port 587:
Error: Unable to connect to inbox - Connection failed to imap.pratt.edu,587: Connection refused

Is there another port I can try, or is there a way to force SSL or check to see if that might be related to the issue I'm having? 

I tried enabling Wordpress debugging, but the wp-content/bp-rbe-debug.log file isn't capturing anything.  Nothing is being written to the file when I save my settings. We're really eager to get this up and running for our users, so any help or guidance would be much appreciated. If necessary, I can arrange for compensation. Thanks.

**Comment by r-a-y** [comment]
Going to close this.  OP is using [this code snippet at the moment](https://github.com/r-a-y/bp-reply-by-email/issues/42#issuecomment-23829888).

Will address the main issue in tickets 42 / 41.
