### ISSUE TITLE
Override certificate error?

### ISSUE THREAD

**Issue by fsnk** [r-a-y/bp-reply-by-email#60]
I get the following error when trying to connect.

Error: Unable to connect to inbox - Certificate failure for mail.[mydomain].com: Server name does not match certificate

I'm on a shared host, and the default server certificate is shared. It's issued to [myhostserver].com. Normally I can just acknowledge the warning, confirm an exception, and connect anyway. (I know I can pay to get a certificate for my domain and then pay my host to install it, but it's a personal site and really not worth the money.)

I can't see a way in the configuration to override or approve the security exception. Halp? :)

**Comment by r-a-y** [comment]
I'm going to close this for #41.
