### ISSUE TITLE
bbPress: New topic subject mangled when using UTF-8

### ISSUE THREAD

**Issue by Muvuk** [r-a-y/bp-reply-by-email#61]
Hi r-a-y!

This plugin is awsome, and the basic function is working well. I have tried your module with bbpress for create group forum topic by email, but the new forum topic title has a wrong character (i think it' coding problem). I see wrong text in database too. 

I tested from UTF8 gmail account to UTF8 gmail and in the mailbox everything is perfect, but in bbpress only the topic body is correct from email body, the topic title is wrong. 

Have you any idea for improve this?

Try this subject: árvíztűrő tükörfúró

**Comment by r-a-y** [comment]
Thanks for the report.

I will take a look at this sometime next week.  Happy New Year!
