### ISSUE TITLE
Does this plug in work with GMail via Google Apps for Business

### ISSUE THREAD

**Issue by globalvillage** [r-a-y/bp-reply-by-email#62]
Hello!  Great plug-in.  I know it works best with a GMail account -- I am presuming it would work just the same with a GMail Account that I have programmed to my own domain so my email is now forum@mydomain.com -- even though it is running off the GMail platform.

Also -- I would love to hire someone for an hour to review my site and make sure I have it set up properly.  It seems to be working fine, but it will be quite active and I want to make sure there will not be any issues.   Anybody qualified and available?

Thank you!

**Comment by r-a-y** [comment]
Sorry for the late reply.

Although I haven't tested, your Google Apps email address should work just fine.
