### ISSUE TITLE
Sending mails per Manrill

### ISSUE THREAD

**Issue by KollektivMuenchen** [r-a-y/bp-reply-by-email#63]
Hey Ray,

genius guy! This is such a useful and awesome Plugin. Thank you so much for your work on this.
I just face a small problem since I decided to use mandrill to deliver the emails from my network. There I set up a template, which I'm using now. Somehow and somewhere the --- Reply ABOVE this line --- gets lost. That's very sad, as the mailing is much more reliable and beautiful now.

Any idea how I can fix that?

Best regards,

Philipp

**Comment by r-a-y** [comment]
If you're using the wpMandrill plugin, don't use it.  Instead, use Mandrill's SMTP credentials with a SMTP plugin.

Read this article for more info:
http://help.mandrill.com/entries/21738447-Can-I-use-Mandrill-to-send-email-through-my-content-management-system-CMS-

See if that works and report back.

**Comment by KollektivMuenchen** [comment]
Hi ray,

thank you for your answer. I just tried everything and the emails are send by smtp now. But I've no idea how to set up the smtp headers to let me set the templates (stored at mandrill) I would like to use. 
That was pretty easy with the plugin before and sadly I wasn't able to fid an already existing solution. ;)

Best regards,
Philipp

**Comment by r-a-y** [comment]
It's a problem with the wpMandrill plugin.  They are doing something with the `'wp_mail'` filter that is preventing the RBE headers from being injected.  I don't have time to look into what they are doing at the moment.

In the meantime, if you want to use a SMTP plugin with Mandrill and have their tracking functionality, you'll need to add in the headers yourself via a custom plugin:
http://help.mandrill.com/entries/21688056-Using-SMTP-Headers-to-customize-your-messages

Going to close this as invalid.
