### ISSUE TITLE
Plug-in sending out emails to all old posts - users receive hundred of emails

### ISSUE THREAD

**Issue by globalvillage** [r-a-y/bp-reply-by-email#64]
Hello.  I have this plug-in installed and configured as described in the Wiki.  However, as I add people to the Group which has access to the Forum and indicate that they receive "all email", the users begin receiving hundreds of emails from old posts.   How can I avoid this?  I am afraid to launch this again as I don't want to flood user in-boxes with emails.  

On a separate note, would you be willing to give me a few hours of your time (at your standard rate, of course) to review the current installation and configuration of the plug-in to be sure that I have done it correctly?   Thank you.

**Comment by r-a-y** [comment]
> However, as I add people to the Group which has access to the Forum and indicate that they receive "all email", the users begin receiving hundreds of emails from old posts.

This shouldn't happen.  What mode are you using?  IMAP or Inbound Email?  I'm guessing IMAP.  If so, make sure you are using a brand-new email account with no existing emails in the inbox.

"All Email" is not from this plugin; it's from the BP Group Email Subscription plugin.  That plugin should not send older forum posts.

To test if it is a problem with RBE, deactivate the plugin and add members to the group again.  See if you get the same issue.

**Comment by r-a-y** [comment]
I'm going to close this ticket since there hasn't been an update about this.  Feel free to reopen if you're still experiencing an issue.
