### ISSUE TITLE
bbPress - Remove flood check when replying by email

### ISSUE THREAD

**Issue by globalvillage** [r-a-y/bp-reply-by-email#66]
I am getting this notice occasionally when testing posting via email to the Forum, even though I am a member of the group.   

"Could not be posted because you are no longer a member of this group.  To comment on the forum thread, please rejoin the group"

It appears to happen when I post several times with 10 minutes.   Is there some way to correct this or remove any time and/or frequency restrictions? 

Thank you.

**Comment by globalvillage** [comment]
It seems that maybe this issue has been resolved, but I still occasionally get these notices --

Could not be posted because it appears that you are trying to post too often. Please wait a few minutes and try again

What are the limitations and can I remove them?   Thank you.

**Comment by r-a-y** [comment]
I guess I can think about removing the flood check in bbPress when replying by email.
