### ISSUE TITLE
Possible features -- Email attachments?   HTML emails?   Topic history included in emails?

### ISSUE THREAD

**Issue by globalvillage** [r-a-y/bp-reply-by-email#67]
Can the plug-in be configured to do any of the following - 

1.   Email attachments that will be posted as part of the forum?   
2.   Can emails that get sent out be in HTML?
3.   Can the emails include the whole topic history?   So you can see the entire discussion rather than just the most recent reply?

**Comment by r-a-y** [comment]
1. Modifying the body of the email content should not be the job of this plugin.  It should be the job of the plugin that is sending the email.  In your case, that would probably be the BP Group Email Subscription plugin.
2. HTML sending should not be part of this plugin.  You can try WP Better Emails for BP - https://github.com/r-a-y/wp-better-emails-for-bp
3. See point 1.
