### ISSUE TITLE
Postmark Support for RBE?

### ISSUE THREAD

**Issue by bennyp123** [r-a-y/bp-reply-by-email#68]
Howdy,
Is postmark support on the roadmap for inbound email processing with reply-by-email plugin?

**Comment by r-a-y** [comment]
Postmark gives you 25,000 initial credits for free.

This will last you for awhile (depending on the amount of email you use on your site), but it's something that you would have to pay for after you pass the free limit.

RBE currently has support for Mandrill, which offers 12,000 emails each month for free.  This should be enough for most sites.

Adding support for another inbound email provider is possible, but it takes development.

----

If you are a plugin developer, there is a hook that you can use to register a new inbound provider class:
https://github.com/r-a-y/bp-reply-by-email/blob/master/bp-rbe-core.php#L190

Then, your class should have two things:
* A static `$name` variable (eg. 'Postmark')
* A `webhook_provider()` class method.  This method will need to be written according to Postmark's Inbound API for signing and validating the POST response.  Here's a URL I found with some documentation: http://developer.postmarkapp.com/developer-process-parse.html

See how the Mandrill inbound provider class is written for more info:
https://github.com/r-a-y/bp-reply-by-email/blob/master/includes/bp-rbe-classes.php#L1223

The last step to tie everything together is configuring Postmark as an inbound provider and to set up their [inbound domain forwarding](http://developer.postmarkapp.com/developer-process-domain.html).  Lastly, select 'Postmark' as RBE's inbound provider and fill in the `Inbound Domain` setting into the RBE admin settings panel with the domain you set up.

This write-up is actually a good developer document for people wanting to add additional inbound providers to RBE.  So thanks for getting me started on that!

**Comment by boonebgorges** [comment]
Today, Mandrill announced some pretty big changes to their business model: http://blog.mandrill.com/important-changes-to-mandrill.html 

There's a lot to digest, but some things that stand out to me are:
* Mandrill no longer has a free tier (doing away with the biggest argument in favor of making it the sole/main provider for RBE)
* It's becoming a sub-product to MailChimp, which RBE users may neither need nor want.
* Mandrill will now require DKIM and SPF DNS records

This change is going to be a huge PITA for existing Mandrill users, and the whole thing reads to me like a way of deemphasizing the product internally.

Anyway, this is just a small argument that it's worth considering (more than before, perhaps) built-in support for another provider. Postmark is a good start.

**Comment by r-a-y** [comment]
Super groan! :(

I'll make Postmark support a priority.

**Comment by r-a-y** [comment]
Postmark support is added as of commit 12f2782.

Commit message references the wrong issue!
