### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by mtadams4** [r-a-y/bp-reply-by-email#69]
Fatal error: Call-time pass-by-reference has been removed; If you would like to pass argument by reference, modify the declaration of apply_filters(). in /wp-content/plugins/r-a-y-bp-reply-by-email-7301e4c/includes/bp-rbe-functions.php on line 778

Fatal error: Call to undefined function groups_get_current_group() in /public_html/wp-content/plugins/bp-reply-by-email-master/includes/bp-rbe-functions.php on line 1274

**Comment by r-a-y** [comment]
Thanks for the report, @mtadams4.

I've fixed the fatal error call that you were experiencing for the second instance.  For the first error, can you try updating to the latest master and report back?  I do not see the specific reference you are relating to.

**Comment by mtadams4** [comment]
Got the latest from here:
https://dev.commons.gc.cuny.edu/2012/07/27/introducing-buddypress-reply-by-email-beta/

Got this error:
*Fatal error*: Call-time pass-by-reference has been removed; If you would
like to pass argument by reference, modify the declaration of
apply_filters(). in
*/public_html/wp-content/plugins/r-a-y-bp-reply-by-email-7301e4c/includes/bp-rbe-functions.php*
on
line *778*

How can I get you the specific reference for you to see?

Thank you for getting back so quickly!


On Tue, Sep 22, 2015 at 12:43 PM, r-a-y <notifications@github.com> wrote:

> Thanks for the report, @mtadams4 <https://github.com/mtadams4>.
>
> I've fixed the fatal error call that you were experiencing for the second
> instance. For the first error, can you try updating to the latest master
> and report back? I do not see the specific reference you are relating to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r-a-y/bp-reply-by-email/issues/69#issuecomment-142344430>
> .
>



-- 
Jonah G. Bernstein
(617) 383-7817
jonahbernstein@gmail.com

**Comment by r-a-y** [comment]
Use this version and report back:
https://github.com/r-a-y/bp-reply-by-email/archive/master.zip

**Comment by mtadams4** [comment]
It installed without errors. However when person2 is replying to person1's
message, person2's reply goes to BuddyPress's inbox but it is not getting
sent to Person1's email.

I'm on the latest version of BuddyPress but I'm happy to downgrade if that
helps.

On Tue, Sep 22, 2015 at 12:58 PM, r-a-y <notifications@github.com> wrote:

> Use this version and report back:
> https://github.com/r-a-y/bp-reply-by-email/archive/master.zip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r-a-y/bp-reply-by-email/issues/69#issuecomment-142348387>
> .
>



-- 
Jonah G. Bernstein
(617) 383-7817
jonahbernstein@gmail.com

**Comment by r-a-y** [comment]
I need more details.

- What mode are you using? IMAP or Inbound?
- What type of message is person 2 replying to?  An at-mention, PM or forum post?
- Can you check the debug log and see what that says? `/wp-content/bp-rbe-debug.log`

You might have to try deactivating and reactivating the plugin and sending a new test message.

If your site is on a shared host, I would also recommend trying Inbound Mode instead of IMAP.  Please read the Starter Guide for more details:
https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide

**Comment by mtadams4** [comment]
I'll get you those details ....
Just wanted to say that I'm using RBE on two website. The first one
installed no problem a few days ago - no errors and it works fantastic. I
just tested it again and it's working great.

The second website is where we're having issues. I have no idea why they
would be different. I even tried uploading copies from wordpress and RBE
from website 1 into website 2 and it didn't work.

On Tue, Sep 22, 2015 at 1:24 PM, r-a-y <notifications@github.com> wrote:

> I need more details.
>
>    - What mode are you using? IMAP or Inbound?
>    - What type of message is person 2 replying to? An at-mention, PM or
>    forum post?
>    - Can you check the debug log and see what that says?
>    /wp-content/bp-rbe-debug.log
>
> You might have to try deactivating and reactivating the plugin and sending
> a new test message.
>
> If your site is on a shared host, I would also recommend trying Inbound
> Mode instead of IMAP. Please read the Starter Guide for more details:
> https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r-a-y/bp-reply-by-email/issues/69#issuecomment-142355390>
> .
>



-- 
Jonah G. Bernstein
(617) 383-7817
jonahbernstein@gmail.com

**Comment by r-a-y** [comment]
The difference is probably due to the hosting environment.

I'm going to close this for now as the fatal errors have subsided.
