### ISSUE TITLE
"NOT CONNECTED", and nothing being written to debug log

### ISSUE THREAD

**Issue by boonebgorges** [r-a-y/bp-reply-by-email#71]
I'm testing RBE on a staging server for a new client, using IMAP + Gmail. All the checks that take place when I save the settings are passing, but I'm seeing the "Reply By Email is currently NOT CONNECTED. Please refresh the page to initiate a connection." notice on the admin panel. Refreshing the page doesn't make it go away.

I enabled `BP_RBE_DEBUG` mode to track the problem, but *nothing* is being written to the debug log. (Just to test it, I put `bp_rbe_log( 'foo' )` into the global space of one of the plugin files, and it worked.)

I'm assuming that some check is preventing RBE from its regular attempts to establish an IMAP connection. I thought maybe you could answer me in 30 seconds what it would take me an hour to debug :)

**Comment by r-a-y** [comment]
It could be a permissions problem with creating the initial log.

Try creating bp-rbe-debug.log manually first.  I should probably just 
create this on plugin activation.

**Comment by r-a-y** [comment]
Sorry, I misread the initial report!

It appears that you can write to the log.  What happens when you deactivate and reactivate the plugin?  Is anything written to the log then?

**Comment by boonebgorges** [comment]
Deactivating, I did get a log message "Plugin deactivated!". 
Reactivating, I got nothing, and the same behavior as before *headscratch*

**Comment by r-a-y** [comment]
Maybe try Inbound mode?

For IMAP, the inbox check relies on wp_remote_post(), which runs on the 
'shutdown' hook.  I'm guessing this might be where the hiccup is.

Do you see any '?bp-rbe-ping=1' entries in the access log?

**Comment by r-a-y** [comment]
I finally encountered this issue today! :)

Problem is due to GMail's increased security settings.

You need to login to Google and then visit this page:
http://www.google.com/accounts/DisplayUnlockCaptcha

And click on the blue "Continue" button.

Next, go to RBE's settings page and click on "Save Changes" so RBE will initiate an IMAP login attempt.  Now RBE should say it is Connected.

Will add this info to the wiki.

Going to close this one.

**Comment by andrew01ait** [comment]
I went through the steps of granting access for 'unsecure apps' within google and also did the DisplayUnlockCaptcha. However I am still experiencing the same problems as described by boonebgorges.

Only the deactivation message is written to the logs, nothing else and the plugin remains at the state
"Reply By Email is currently NOT CONNECTED. Please refresh the page to initiate a connection."

Any suggestions, hints on how I could debug that one?

**Comment by r-a-y** [comment]
You might have to run through the steps a few times in order for Google to properly see the IMAP connection.  I would suggest doing that first.

You're not the only one running into these problems.  If you do a search on Google for `php imap gmail`, you will get similar reports of the same issue for other PHP mail applications.

The alternative is to add support for oAuth 2.0 for PHP's IMAP module as PHP doesn't support oAuth by default, I'd have to use some library for this.  However, this is not a priority for me at the moment.  Pull requests welcome.

If you cannot get GMail to work, I would suggest either using a different IMAP email provider that supports plus addressing.  Or try [Inbound Mode](https://github.com/r-a-y/bp-reply-by-email/wiki/Starter-Guide).
