### ISSUE TITLE
Amazon SES support

### ISSUE THREAD

**Issue by boonebgorges** [r-a-y/bp-reply-by-email#76]
See also #68, and especially https://github.com/r-a-y/bp-reply-by-email/issues/68#issuecomment-188592789

Amazon SES seems like it might be the cheapest ready-made alternative to Mandrill. It would be interesting to see what an integration might look like.

A brief look at the documentation suggests that this'd have to be accomplished by having SES send SNS notifications, and then routing these notifications to the WP site http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html

**Comment by r-a-y** [comment]
Going to close this in favor of #77.

If we decide to implement Amazon SES, I'll reopen this issue.
