### ISSUE TITLE
debug log not logging and no user found at that email address

### ISSUE THREAD

**Issue by jrb9406** [r-a-y/bp-reply-by-email#78]
I have setup bp-reply-by-email using sparkpost. I walked through the installation steps here https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost , and everything seemed to go fine.

I tested using group forum posts and group activity. All members to my group are able to receive all emails (any new post or mention generates an email). When my users reply to the email, they get a response stating that there was a server error (550 No Such User Here). This is the same response that is received if a user sends an email directly to the forum for posting.

Is there something that I might be missing here? I tried checking the debug log, but it only says that the plugin was deactivated. The plugin has since been reactivated (I checked multiple times), but there are no new logs.

**Comment by r-a-y** [comment]
> When my users reply to the email, they get a response stating that there was a server error (550 No Such User Here).

Can you paste the response?

Ensure that you configured everything on SparkPost correctly.

In the email that you want to reply to, what does the `Reply-To` email address say?  Ensure that the subdomain you created on SparkPost is in that address.  If you recently configured this, you might have to wait until the subdomain DNS has populated on SparkPost.

If nothing is being logged, then there is a problem with SparkPost sending the email response back to your website.

Is your site password-protected?  If so, the webhook will not be able to post properly.  Your webhook URL needs to be located at a publicly-available URL.  Change the `target` field to a publicly-accessible URL on your WordPress install in this step:
https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost#5-in-sparkpost-register-the-webhook

Ensure that the SparkPost console does not show any errors after you submit.

If you are not a developer, you might want to try one of the other Inbound Providers since they have a better admin interface.

**Comment by jrb9406** [comment]
EMAIL RESPONSE POSTED BELOW:

Delivery to the following recipient failed permanently:

     2e905dde0b9a50b1f231eb353c285fb0@post.nuc-net.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain post.nuc-net.com [69.195.92.53].

The error that the other server returned was:
550 No Such User Here


----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:in-reply-to:references:date:message-id:subject:from:to;
        bh=Fw+vO8nYMuTU4knO4MdRWr0wze8bdTeGCPiy18zO0qY=;
        b=dIb9DuQ6P1x3snMaclivdB/0hyfAX1o05IF2xBMfl79Q0xBpCG7d5Ydh5s+pxvV0MG
         vOmFx+K3JOmkVKNF83FaVa4gG/RMT+BaCo96DfWZV53Ffh3tx5zw+HmoFVnpQb2l9Cfa
         UXWsTMf7Gzq5ED5KRT60162upx3fwOyOcKHeX4Yb7ArNg204x75rIPlgcgLLEOc0yV4u
         VEjcaNjZQ3pszg9oeN8HPxDtqjJrSXkwm+2enlxA16eTVprb5GcnCEtiCYhasA77iJu9
         i+3nI2t2bH13juOEQGJNEPWRjATYTgdDN2c2wu0QBqbUq3qsy9Lj/2p4ePm5qqm2x4Ub
         LWSg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:mime-version:in-reply-to:references:date
         :message-id:subject:from:to;
        bh=Fw+vO8nYMuTU4knO4MdRWr0wze8bdTeGCPiy18zO0qY=;
        b=cQTHYTYZN6gexJ9elqTs9kHkc4njtUvYBF0Ca/ZX+pl+BBK/kyeChHX6rkwQN2pH5F
         y2DdxYjHxnuCWeMwHTyLu0vk+Fu3L65NOZGixzye96xW85llG9j8K27sfOOoo6f/oWoI
         K7qRSrp/woU5B+reSRc+EQgOjMfVTZJo+dliQrSC0JoeUwoQO5co9BN1X9yXZh94B1wJ
         fZiZFpvXLrJ+Rd8wW3ax+VciBbMdPu+B8+4Gp4ClHpOrQhYbUcg3L4U5R8G+UPk/L/rX
         QjpUfQfi1c7MrHDL2YgkFLOBmzbPptwgOi/aMlbx7yStNJ7gWuOeK0CGxobelNvT3YI8
         npWQ==
X-Gm-Message-State: AOPr4FWu7j3Bx3CDFULlQAHrkaOMU2f2cOMhKNto5NXc448ClOZk8z7ozI6JRAIbVyTlFbkpZFpZsbnbGIvMRg==
MIME-Version: 1.0
X-Received: by 10.129.137.4 with SMTP id z4mr269516ywf.213.1462930840264; Tue,
 10 May 2016 18:40:40 -0700 (PDT)
Received: by 10.37.13.140 with HTTP; Tue, 10 May 2016 18:40:40 -0700 (PDT)
In-Reply-To: <05eb09116f4f7f13be2658b434e2f68c@www.nuc-net.com>
References: <05eb09116f4f7f13be2658b434e2f68c@www.nuc-net.com>
Date: Tue, 10 May 2016 21:40:40 -0400
Message-ID: <CAO7yMaihgcvoWaGni8kvdpgR=j0ECmGm=gtpDdG0PwxpifzOjA@mail.gmail.com>
Subject: Re: [NUC-NET] Jim mentioned you in an update
From: Jim Breunig <jrb9406@gmail.com>
To: 2e905dde0b9a50b1f231eb353c285fb0@post.nuc-net.com
Content-Type: multipart/alternative; boundary=94eb2c06c10010a87b053287211c

> in the email that you want to reply to, what does the Reply-To email address say? Ensure that the subdomain you created on SparkPost is in that address. If you recently configured this, you might have to wait until the subdomain DNS has populated on SparkPost.

See above for reply-to. It does contain the subdomain. It's been about 24 hours, but perhaps it needs more time.

> Is your site password-protected? If so, the webhook will not be able to post properly. Your webhook URL needs to be located at a publicly-available URL. Change the target field to a publicly-accessible URL on your WordPress install in this step:
https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost#5-in-sparkpost-register-the-webhook

The forums are password protected, and I have the site locked down, but the home page is not password protected. The URL used for the target does not require a login.

> Ensure that the SparkPost console does not show any errors after you submit.

When I set this up, I did not receive any errors.

> If you are not a developer, you might want to try one of the other Inbound Providers since they have a better admin interface.

I will give it a little more time, and I will try another provider. Do you have recommendations? I appreciate all of your help.

**Comment by r-a-y** [comment]
Thanks for posting the email response.

Did you add SparkPost's MX entries to your custom subdomain?
https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost#2-create-a-subdomain-at-your-domain-registrars-dashboard
https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost#3-add-sparkposts-mx-records-for-your-new-subdomain

If you did, you'll probably still need to wait for the DNS to propagate.

**Comment by jrb9406** [comment]
> Did you add SparkPost's MX entries to your custom subdomain?

I did. I host with Bluehost, and I was not able to add DNS records to the subdomain itself. I asked Bluehost, and they said that the MX records for the domain also apply to the subdomain, so putting them there would be the same.

I'm not terribly familiary with DNS records, so I hope that's true. I didn't get any errors when setting up sparkpost, so I assumed to was ok.

**Comment by r-a-y** [comment]
> I asked Bluehost, and they said that the MX records for the domain also apply to the subdomain, so putting them there would be the same.

This sounds wrong to me.  It needs to be on the subdomain.

See this blog post for more details:
https://woorkup.com/point-mx-records-to-bluehost/

**Comment by jrb9406** [comment]
Just finished talking with Bluehost. Apparently they can do this (last person must not have known or misunderstood). I'll check back tomorrow to let you know. Thanks so much!

**Comment by jrb9406** [comment]
Eureka! Got it. 

Bluehost wasn't terribly helpful here though. I thought about it a little more, and it made sense to put my subdomain as the host for the MX record (seems obvious now). I did that, and now it is fully functional. Thank you!

**Comment by r-a-y** [comment]
Glad everything worked out!
