### ISSUE TITLE
Using SendGrid: "Mail delivery failed: returning message to sender"

### ISSUE THREAD

**Issue by devinbalkind** [r-a-y/bp-reply-by-email#80]
Hi. Thanks for this really exciting plugin.

I've set up the plugin using SendGrid, and following all the instructions (I think) in the wiki. 

Emails are flowing from the system, but the replies aren't work. 

I get the following error when I reply to an email:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  310482fa9683c53ec8e37190d829282336189766b5e301fe49567cfdbe240dd4@reply.mydomain.org
    No Such User Here
Reporting-MTA: dns; host25.registrar-servers.com

Action: failed
Final-Recipient: rfc822;310482fa9683c53ec8e37190d829282336189766b5e301fe49567cfdbe240dd4@reply.mydomain.org
Status: 5.0.0

It looks to me like the system isn't recognizing the long string before the @ symbol.

Another thing: I haven't pasted the Key in the settings page anywhere. Am I supposed to do that? 

Thanks so much.

**Comment by r-a-y** [comment]
Your problem is very similar to #78.

You need to ensure that your custom subdomain is using SendGrid's DNS entries.

Read step three again:
https://github.com/r-a-y/bp-reply-by-email/wiki/SendGrid#2-create-a-subdomain-at-your-domain-registrars-dashboard

**Comment by devinbalkind** [comment]
Thanks for the quick reply.

I created a reply. subdomain, set up the MX record at the reply. subdomain
and filled out the Inbound Parse with reply. and the full domain - spam
check and send raw is off.

Do I need to add my domain as a white label via SendGrid?

**Comment by r-a-y** [comment]
Test if your subdomain is resolving to SendGrid here:
http://mxtoolbox.com/

In your original post, you posted this: `Reporting-MTA: dns; host25.registrar-servers.com`

Which means your subdomain is not resolving to SendGrid.  This is telling me that you haven't configured your subdomain properly to use SendGrid.

You have to add SendGrid's DNS MX records at your domain registrar's dashboard page.

**Comment by devinbalkind** [comment]
Hmm. I did add the MX record.

mxtoolbox says:

PrefHostnameIP AddressTTL
10 mx.sendgrid.net
<http://mxtoolbox.com/SuperTool.aspx?action=mx%3areply.bankofmutualinterest.org&run=toolpage#>
167.89.125.4
<http://mxtoolbox.com/SuperTool.aspx?action=mx%3areply.bankofmutualinterest.org&run=toolpage#>
20
min Blacklist Check
<http://mxtoolbox.com/SuperTool.aspx?action=mx%3areply.bankofmutualinterest.org&run=toolpage#>
      SMTP Test
<http://mxtoolbox.com/SuperTool.aspx?action=mx%3areply.bankofmutualinterest.org&run=toolpage#>
I looked rechecked the MX records, the SendGrid Inbound Parse and my
WordPress backend to make sure they all match and they do.

Any other ideas?

**Comment by r-a-y** [comment]
Did you add the MX record recently?

Can you try another reply-by-email attempt on your BuddyPress install?  Also check the debug log to see if SendGrid sent any webhook responses back to your server at `/wp-content/bp-rbe-debug.log`.

**Comment by devinbalkind** [comment]
I added the MX record over an hour ago.

I tried again. It's working with a Google Apps powered email account but
not from a Namecheap/Cpanel one that has the same domain name as the
website's URL.

Do you think there's a specific issue with email addresses at the same
address as the website URL?

**Comment by r-a-y** [comment]
It can take upwards of 48 hours for the MX record to fully propagate.

Maybe check back in 48 hours and keep me apprised.

**Comment by devinbalkind** [comment]
Okay will do. Thanks.

**Comment by r-a-y** [comment]
Any updates, @devinbalkind?

**Comment by r-a-y** [comment]
I'm going to close this for the moment, but feel free to amend this ticket with further details, @devinbalkind.
