### ISSUE TITLE
Reply to email not going to inbox or showing notification.

### ISSUE THREAD

**Issue by dreadedhamish** [r-a-y/bp-reply-by-email#81]
I've just installed bp-reply-to-email (latest commit  f7b5c6a).
I've set up Sendgrid.

I sent an email to a test user:
1. email was successfully sent to user.
2. replied, and email was received by site, and email sent to test user.

I can see the response when I go to sent messages, BUT it doesn't go to the inbox, or add a notification.

Log:
[06-Jun-2016 16:12:38] - Operating mode switched to inbound -
[07-Jun-2016 02:39:43] - SendGrid webhook received -
[07-Jun-2016 02:39:43] Message #1: email headers successfully parsed
[07-Jun-2016 02:39:43] Message #1: address tag successfully parsed
[07-Jun-2016 02:39:43] Message #1: params = Array
(
    [m] => 6
)

[07-Jun-2016 02:39:43] Message #1: body contents - response from test email to site

On Tue, Jun 7, 2016 at 12:38 PM, admin <
[07-Jun-2016 02:39:43] Message #1: this is a private message reply
[07-Jun-2016 02:39:44] Message #1: PM reply successfully posted!
[07-Jun-2016 02:39:44] - Webhook parsing completed -

**Comment by r-a-y** [comment]
I cannot duplicate this.

RBE sends a private message with BuddyPress' `messages_new_message()` function.  That function should trigger sending a new notification.  If you viewed the message thread on your website, BuddyPress silently marks all messages in that thread as read.  

However, the message thread should still show up in your "Messages > Inbox" page, it just will not be highlighted as unread.

You can tell if the notification was sent by checking your "Notifications > Read" page and seeing if the message resides there.

**Comment by dreadedhamish** [comment]
On further investigation:

The reply from email arrives at the site, and automatically appears as read.  
There is nothing in notification (read or unread).
On marking the message 'Unread' it does not go to the inbox, and notification (read and unread) are still empty.

Where would you suggest I look for errors?

**Comment by r-a-y** [comment]
Do notifications get created when you are replying to a private message normally on your website and not via email?

**Comment by dreadedhamish** [comment]
Resolved.  
I was using my name@gmail.com, and for a test account name+test@gmail.com, and I think that messed with it.  Messaging a regular user back and forth worked perfectly with notifications.

Thanks so much for this functionality - it's super impressive.

**Comment by r-a-y** [comment]
> I was using my name@gmail.com, and for a test account name+test@gmail.com, and I think that messed with it.

Yes, that is definitely the problem.  User accounts cannot have address tags in them.  I guess this should be added somewhere in the documentation.

Thanks for saving me another round of debugging! :smile:
