### ISSUE TITLE
Default marker gets corrupted by certain mail client

### ISSUE THREAD

**Issue by GuillaumeFromage** [r-a-y/bp-reply-by-email#83]
Hi, 

I'm experiencing troubles using the standard end-of-email marker (--- Reply ABOVE THIS LINE to add a comment ---). Some email clients, including roundcube, will sometime change -- to - or --- to — (some utf-8 weird char) in the response. It would be really nice to find a marker that doesn't get confused by default. 

I'd propose ==Reply ABOVE THIS LINE to add a comment==  as that's what redmine uses and I never had much issues like that with redmine (but yeah, mutt users aren't getting a lot of these issues :D).

G

**Comment by r-a-y** [comment]
Hi @GuillaumeFromage,

I've added a new filter just now so you can change the RBE marker for your install.

Add this to your theme's `functions.php` or to `wp-content/plugins/bp-custom.php`:

```
// Changes the RBE marker to something else.
add_filter( 'bp_rbe_get_marker', function( $retval ) {
    return '==Reply ABOVE THIS LINE to add a comment==';
} );
```

I might consider changing this by default, but for now this filter should be enough to fix your problems.

**Comment by GuillaumeFromage** [comment]
Thanks so much for a fast response !

I tried that, did the git pull on the module, added a bp-custom.php (with a <?php at the beginning) and did test if it loads (print("tessssssst");) which worked, but I still get the error. I'm sadly really new to wordpress, and I've some friends to look at your patch, which seems fine, but if you got time, it would be nice if you could test and see if the problem is on our side !

Thanks a lot !

**Comment by r-a-y** [comment]
Did you try sending a new email so your custom RBE marker is in place?

**Comment by GuillaumeFromage** [comment]
Yes, it is still sending ""--- Reply ABOVE THIS LINE to add a comment --- ""

And when I send ==  Reply ABOVE THIS LINE to add a comment == it doesn't parse it either.

**Comment by r-a-y** [comment]
I forgot to replace a hardcoded instance of the marker.

Once you've pulled the latest commit, deactivate and reactivate RBE and send a new email to test.

**Comment by GuillaumeFromage** [comment]
Okay, I got everything to work "right". The parsing wasn't happening, so I figure the parser was loaded without the bb-loader system, hence not having the filter defined, so I added require_once( WP_PLUGIN_DIR . '/buddypress/bp-loader.php' ); at line 506, in the get_body function, but it didn't work (it seemed to interfere with "$body = apply_filters( 'bp_rbe_parse_html_email', $body );" , so I hardcoded the == in the bp_rbe_get_marker function.  I'll pull your code over my hack whenever you find a solution that little dependency issue !

Thanks again so much !

**Comment by r-a-y** [comment]
>  so I added require_once( WP_PLUGIN_DIR . '/buddypress/bp-loader.php' ); at line 506,

This shouldn't be necessary.  Please follow what I outlined in the comment above and remove any modifications that you made to the core code.

**Comment by r-a-y** [comment]
Any updates, @GuillaumeFromage?

**Comment by r-a-y** [comment]
Going to close this one for now.
