### ISSUE TITLE
How to Filter Registration Confirmation Emails from RBE?

### ISSUE THREAD

**Issue by BillW2016** [r-a-y/bp-reply-by-email#85]
Hi, first of all THANKS so much for your work on this plugin!  It's VERY useful and is a MUCH appreciated enhancement to BuddyPress.  With respect to our Buddypress groups, it's doing a great job!

I am having a problem however.  RBE is intercepting ALL outgoing emails (not just Buddypress Group Activity) and is putting this warning on top of them:
  '--- Replying to this email will not send a message directly to the recipient or group ---'

The most important one is the Registration Confirmation/Welcome email sent to new users on registration.  We are using the standard WP registration process and emails (not buddypress) and we have customized the message (by adding 'wp_new_user_notification' in our site plugin).  This heading across the top of ALL outgoing emails isn't desirable and in this case isn't correct - the new user can, in fact, reply to that email to contact us.

**My question is:**
How can I filter out the Registration/Welcome Email (and any others I wish, like those from our Contact Form 7) so that RBE doesn't do anything with them?

Thanks in advance for your help!

**Comment by r-a-y** [comment]
@BillW2016 - I answered a similar question here:
https://wordpress.org/support/topic/selectively-use-reply-by-email-avoid-woocommerce-newsletter-etc/

Let me know if that answers your question.

**Comment by BillW2016** [comment]
Perfect, thanks! Exactly what we needed.
