### ISSUE TITLE
Fatal error when debug-bar plugin is active

### ISSUE THREAD

**Issue by modelm** [r-a-y/bp-reply-by-email#86]
When the debug-bar plugin is active, bp-reply-by-email tries to load a nonexistent file and causes a fatal error:

https://github.com/r-a-y/bp-reply-by-email/blob/master/includes/class.plugin-update-checker.php#L658

**Comment by r-a-y** [comment]
Thanks for the report.

I've just added a commit that comments out the Debug Bar integration from PUC.  This should fix the fatal error.
