### ISSUE TITLE
reply to forum post fails only from outlook

### ISSUE THREAD

**Issue by bricoll** [r-a-y/bp-reply-by-email#93]
Hello r-a-y,

Here's what the rbe debug.log records for all attempts from outlook to reply by email to forum post:

[02-Mar-2017 20:39:12] - Postmark webhook received -
[02-Mar-2017 20:39:12] Message #1: email headers successfully parsed
[02-Mar-2017 20:39:12] Message #1: address tag successfully parsed
[02-Mar-2017 20:39:12] Message #1: error - no parameters were found
[02-Mar-2017 20:39:12] - Webhook parsing completed -

Am using Postmark.

Works fine when RBE from Gmail.

Have you heard of problems with outlook?

Thank you,

B

**Comment by r-a-y** [comment]
Make sure that your WP user's email address matches the one that you are replying from.

If your WP user email address doesn't match, then RBE will fail.  For example, your email client might be set up to reply from a different email address from the one you registered in WordPress or if you are using address tags in your WP email address such as `user+spam@example.com`.

If you are sure that your email address matches, I did also add a fix for Postmark recently regarding #90.  You could try downloading the latest development version and see if that fixes the problem as well:
https://github.com/r-a-y/bp-reply-by-email/archive/master.zip

If you are still running into problems, I'll look into your problem with Outlook soon.

**Comment by bricoll** [comment]
After checking the match for email addresses to confirm, I tried the latest version as suggested, and it worked!

This was far away the best support I've ever received r-a-y! 

Thank you so much!

**Comment by r-a-y** [comment]
Awesome!  Closing this one.
