### ISSUE TITLE
Issues with Postmark

### ISSUE THREAD

**Issue by bricoll** [r-a-y/bp-reply-by-email#98]
R-a-y,

I've installed the plugin and gotten it working several times. Believe I followed all the same steps for this new install, but I can't get it to work. De-bug log says no user id found.

Do you have a suggestion related to what the problem might be?

As always, thanks for whatever help you might be able to proved.

--B

![debug_log](https://cloud.githubusercontent.com/assets/16137382/25280117/d02d9726-2676-11e7-9ca8-b49b9935af26.JPG)

**Comment by r-a-y** [comment]
Is your user using an alias for their email address like `user+test@example.com`?  If so, then RBE will fail.

It's also possible that Postmark changed something in their email headers that has broken how the email address is parsed (see #90).  But I won't know until I do some testing.  Is Postmark working on other installs?

**Comment by bricoll** [comment]
Thanks R-a-y,

No, not using aliases. And I think #90 got fixed in a later build. I don't think it's Postmark because it IS working for me on another site.

Trying reinstalling now to see if maybe I missed something the first time around.

--B

**Comment by bricoll** [comment]
Same error after reinstall.  :-(

**Comment by r-a-y** [comment]
You might want to check a similar report you made in #93.

Double check that the email address that is being used in the email client matches the user's email address in WordPress.

**Comment by bricoll** [comment]
Right. I remember #93. The fix there was to use a more recent build. 
And yes, the addresses are the same in header and Wordpress user's email address.

**Comment by r-a-y** [comment]
I won't be able to look into this until next week at the earliest.

**Comment by bricoll** [comment]
No worries. I appreciate the help. I'll keep working on it on my end and update if I solve.

**Comment by bricoll** [comment]
R-a-y,

After reinstalling cBox and the RBE plugin, deleting the associated Postmark server and creating another for this install, the plugin began working. Thanks again for your help. Hope this fix sticks!

**Comment by r-a-y** [comment]
Glad it works.  Closing.
