### ISSUE TITLE
Possible to post using generic email

### ISSUE THREAD

**Issue by aheicher** [r-a-y/bp-reply-by-email#99]
Hello,

My use case here is fairly simple. My client has a single forum for the vast majority of their users, and wishes these users to be able to post by sending an email to, for example, members@domain.com. Currently, this plugin (which is awesome, by the way) does everything they need except allow posting through a generic address. Right now there are the longer alphanumeric email addresses.

Essentially, the forum exists as a group forum to which all site users have been joined. There is one subforum restricted to a subset of users, which does not necessarily need this feature. I realize that the user and group IDs are encoded in the posting email address, which I understand makes this difficult. Ideally, users could send an email to "members@domain.com" and a post would be made, under their name, in this group forum.

Any idea if something like this is possible? Again - amazing plugin. Thanks!

**Comment by r-a-y** [comment]
I created an extension for this.  See https://github.com/r-a-y/bp-rbe-new-topic.
